const ACTIONS = {
  CHARACTER: {
    WALK: 'WALK',
  },
  GAME: {
    SNAPSHOT: 'SNAPSHOT',
  },
  BROWSER: {
    REGISTER_EVENT_SUCCESS: 'REGISTER_EVENT_SUCCESS',
    UNREGISTER_EVENT_SUCCESS: 'UNREGISTER_EVENT_SUCCESS',
    UPDATE_VIEWPORT_SIZE: 'UPDATE_VIEWPORT_SIZE',
  },
};

export default ACTIONS;
